version: '3.7'
services:
  main: 
    container_name: main
    build:
      context: .
    env_file:
      - .env
    volumes: 
      - .:/app
      - /app/node_modules
    ports:
      - 5001:5001
      - 9229:9229
    command: npm run start:dev
    depends_on: 
      - postgres
    restart: always

  postgres:
    container_name: postgres
    image: postgres:latest
    env_file:
      - .env
    ports:
      - '5433:5433'
    environment:
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
volumes:
  pgdata:
